version: '3'
services:
  cqbackend1:
    image: registry.cn-chengdu.aliyuncs.com/gitee-docker/cq-backend:latest
    ports:
      - '3000:3000'
    depends_on:
      - db
  cqbackend2:
    image: registry.cn-chengdu.aliyuncs.com/gitee-docker/cq-backend:latest
    ports:
      - '3001:3001'
    depends_on:
      - db
  cqbackend3:
    image: registry.cn-chengdu.aliyuncs.com/gitee-docker/cq-backend:latest
    ports:
      - '3002:3002'
    depends_on:
      - db
  cqbackend4:
    image: registry.cn-chengdu.aliyuncs.com/gitee-docker/cq-backend:latest
    ports:
      - '3003:3003'
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - '81:81'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - cqapigateway
  cqapigateway:
    image: registry.cn-chengdu.aliyuncs.com/gitee-docker/cq-apigateway:latest
    ports:
      - '80:80'
    depends_on:
      - cqbackend1
      - cqbackend2
      - cqbackend3
      - cqbackend4
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kch_database
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
