version: '3'
services:
  kchbackend:
    image: registry.cn-chengdu.aliyuncs.com/gitee-docker/cq-images:latest
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kch_database
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
# 这个 docker-compose.yml 并没有用，但依然建议维护
# 在服务器上有维护，如果此配置有修改，请手动复制到服务器部署目录下的yml文件中
