version: '3'
services:
  cqbackend:
    image: registry.cn-chengdu.aliyuncs.com/gitee-docker/cq-backend:latest
    ports:
      - '3000:3000'
    depends_on:
      - db
  cqapigateway:
    image: registry.cn-chengdu.aliyuncs.com/gitee-docker/cq-apigateway:latest
    ports:
      - '80:80'
    depends_on:
      - cqbackend
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: kch_database
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
